
Apps:
  Chrome:
    Package: com.android.chrome
  PlayStore:
    Package: com.android.vending
    Activity: com.android.vending.AssetBrowserActivity
  Whatever:
    iOSBundle: com.apple.Preferences

Devices:
  - role: desktopChrome,desktopChrome2,desktopChrome3
    capabilities:
      chromeOptions:
        args:
          - use-fake-ui-for-media-stream
          - use-fake-device-for-media-stream
          - no-sandbox
    browser: chrome
  - role: desktopFirefox
    browser: firefox
  # COMMAND LINE ROLES
  - role: commandLine,commandLine2,commandLine3
  # ANDROID
  - role: localAndroid
    platform: Android
  # IOS
  - role: localiOS
    platform: iOS
    capabilities:
      udid: $AND_CLI_IOS_DEVICE$


Environments:
  Env1:
    Vars:
      MISC: Running miscelaneous stuff
      TEST: Running tests stuff
    SetupCommands:
      - echo "SetUP"
  Env2:
    Vars:
      MISC: Running miscelaneous stuff 2
      TEST: Running tests stuff 2
    SetupCommands:
      - echo "SetUP 2"
